### ISSUE TITLE
Wiht Fortran code can't go to the line

### ISSUE THREAD

**Issue by armslave7** [jaydenlin/ctags-support#5]
Wiht ```ctags -R -f .ctags``` generate the .ctags file.
If there some files, and can open the right file with the function name selected, but cant go to the right line in the file.
And if the function name is in the same file, there is no action any more.
The language i use is f90(fortran).

**Comment by jtanx** [comment]
This plugin treats the ctags pattern as a normal regex when it's not - it's a vim regex. So if you're trying to lookup a tag where there's brackets on the line, the search will fail (because it's treated as a capturing group or maybe a character class, when it's not). It also doesn't handle if the tags file lists the address as a specific line number instead of a pattern.

**Comment by armslave7** [comment]
From the gif of this plugin, it can go to the right file and line of tag selected, what should i do?
Thank you!

**Comment by jtanx** [comment]
Ah, but in the gif, it's a _Perl_ function with no brackets on the line ;)

For this extension, there's nothing that you can do until it gets fixed by its author. In the meantime, you could try [another](https://marketplace.visualstudio.com/items?itemName=jtanx.ctagsx) extension...

**Comment by armslave7** [comment]
@jtanx I have tryed ```ctags```, it works for several function/subroutine, and mostly, it output ```ctags: no tags found for ***```. And also thank you very much.

**Comment by jtanx** [comment]
@armslave7 thanks for the feedback. For `ctags: no tags found for ***`, that might be a bug in _that_ plugin - it's best to continue discussion there instead of here, since that would be a separate issue to this one.

**Comment by armslave7** [comment]
@jtanx thank you, i have set an issue in ```ctagsx```.
